In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('processed.csv')
df

Unnamed: 0 state_code zip_code           city                  name  \
0             0         CA    92101      San Diego           Bandsintown   
1             1         CA    95032      Los Gatos             TriCipher   
2             2         CA    92121      San Diego                 Plixi   
3             3         CA    95014      Cupertino     Solidcore Systems   
4             4         CA    94105  San Francisco        Inhale Digital   
..          ...        ...      ...            ...                   ...   
918         918         CA    94107  San Francisco               CoTweet   
919         919         MA     1803     Burlington    Reef Point Systems   
920         920         CA    94089      Sunnyvale       Paracor Medical   
921         921         CA    94404  San Francisco               Causata   
922         922         CA    95054    Santa Clara  Asempra Technologies   

     founded_at   closed_at first_funding_at last_funding_at  \
0    2007-01-01  2024-11-22       2009-04-01      2010-01-01   
1    2000-01-01  2024-11-22       2005-02-14      2009-12-28   
2    2009-03-18  2024-11-22       2010-03-30      2010-03-30   
3    2002-01-01  2024-11-22       2005-02-17      2007-04-25   
4    2010-08-01  2012-01-10       2010-08-01      2012-04-01   
..          ...         ...              ...             ...   
918  2009-01-01  2024-11-22       2009-07-09      2009-07-09   
919  1998-01-01  2024-11-22       2005-04-01      2007-03-23   
920  1999-01-01  2024-11-22       2007-06-29      2007-06-29   
921  2009-01-01  2024-11-22       2009-10-05      2011-11-01   
922  2003-01-01  2024-11-22       2006-02-13      2006-02-13   

     age_first_funding_year  ...  avg_participants  is_top500  status  \
0                    2.2493  ...            1.0000          0       1   
1                    5.1260  ...            4.7500          1       1   
2                    1.0329  ...            4.0000          1       1   
3                    3.1315  ...            3.3333          1       1   
4                    0.0000  ...            1.0000          1       0   
..                      ...  ...               ...        ...     ...   
918                  0.5178  ...            6.0000          1       1   
919                  7.2521  ...            2.6667          1       0   
920                  8.4959  ...            8.0000          1       0   
921                  0.7589  ...            1.0000          1       1   
922                  3.1205  ...            3.0000          1       1   

     closed_at_year  closed_at_month  yyyy  mm  month_name  \
0              2024               11  2010   1         Jan   
1              2024               11  2009  12         Dec   
2              2024               11  2010   3         Mar   
3              2024               11  2007   4         Apr   
4              2012                1  2012   4         Apr   
..              ...              ...   ...  ..         ...   
918            2024               11  2009   7         Jul   
919            2024               11  2007   3         Mar   
920            2024               11  2007   6         Jun   
921            2024               11  2011  11         Nov   
922            2024               11  2006   2         Feb   

     first_funding_at_year  first_funding_at_month  
0                     2009                       4  
1                     2005                       2  
2                     2010                       3  
3                     2005                       2  
4                     2010                       8  
..                     ...                     ...  
918                   2009                       7  
919                   2005                       4  
920                   2007                       6  
921                   2009                      10  
922                   2006                       2  

[923 rows x 49 columns]

In [3]:
df2 = df.drop(['Unnamed: 0','state_code','zip_code','city','name','founded_at','last_funding_at','age_first_funding_year','is_CA','is_NY','is_MA','is_TX','category_code','is_software','is_web','is_mobile',
                'is_enterprise','is_advertising','is_gamesvideo','is_ecommerce','is_biotech','is_consulting','is_othercategory','has_VC','has_angel','yyyy','mm','month_name','closed_at','first_funding_at','first_funding_at_month'],axis = 1)                

In [4]:
df2

age_last_funding_year  age_first_milestone_year  age_last_milestone_year  \
0                   3.0027                    4.6685                   6.7041   
1                   9.9973                    7.0055                   7.0055   
2                   1.0329                    1.4575                   2.2055   
3                   5.3151                    6.0027                   6.0027   
4                   1.6685                    0.0384                   0.0384   
..                     ...                       ...                      ...   
918                 0.5178                    0.5808                   4.5260   
919                 9.2274                    6.0027                   6.0027   
920                 8.4959                    9.0055                   9.0055   
921                 2.8329                    0.7589                   3.8356   
922                 3.1205                    4.0027                   4.0027   

     relationships  funding_rounds  funding_total_usd  milestones  \
0                3               3             375000           3   
1                9               4           40100000           1   
2                5               1            2600000           2   
3                5               3           40000000           1   
4                2               2            1300000           1   
..             ...             ...                ...         ...   
918              9               1            1100000           2   
919              1               3           52000000           1   
920              5               1           44000000           1   
921             12               2           15500000           2   
922              4               1           20000000           1   

     is_otherstate  has_roundA  has_roundB  has_roundC  has_roundD  \
0                0           0           0           0           0   
1                0           0           1           1           1   
2                0           1           0           0           0   
3                0           0           1           1           1   
4                0           0           0           0           0   
..             ...         ...         ...         ...         ...   
918              0           1           0           0           0   
919              0           0           1           0           0   
920              0           0           0           0           1   
921              0           1           1           0           0   
922              0           0           1           0           0   

     avg_participants  is_top500  status  closed_at_year  closed_at_month  \
0              1.0000          0       1            2024               11   
1              4.7500          1       1            2024               11   
2              4.0000          1       1            2024               11   
3              3.3333          1       1            2024               11   
4              1.0000          1       0            2012                1   
..                ...        ...     ...             ...              ...   
918            6.0000          1       1            2024               11   
919            2.6667          1       0            2024               11   
920            8.0000          1       0            2024               11   
921            1.0000          1       1            2024               11   
922            3.0000          1       1            2024               11   

     first_funding_at_year  
0                     2009  
1                     2005  
2                     2010  
3                     2005  
4                     2010  
..                     ...  
918                   2009  
919                   2005  
920                   2007  
921                   2009  
922                   2006  

[923 rows x 18 columns]

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age_last_funding_year     923 non-null    float64
 1   age_first_milestone_year  923 non-null    float64
 2   age_last_milestone_year   923 non-null    float64
 3   relationships             923 non-null    int64  
 4   funding_rounds            923 non-null    int64  
 5   funding_total_usd         923 non-null    int64  
 6   milestones                923 non-null    int64  
 7   is_otherstate             923 non-null    int64  
 8   has_roundA                923 non-null    int64  
 9   has_roundB                923 non-null    int64  
 10  has_roundC                923 non-null    int64  
 11  has_roundD                923 non-null    int64  
 12  avg_participants          923 non-null    float64
 13  is_top500                 923 non-null    int64  
 14  status    

In [6]:
df2['age_last_funding_year'] = df2['age_last_funding_year'].astype(int)
df2['age_first_milestone_year'] = df2['age_first_milestone_year'].astype(int)
df2['age_last_milestone_year'] = df2['age_last_milestone_year'].astype(int)
df2['avg_participants'] = df2['avg_participants'].astype(int)

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age_last_funding_year     923 non-null    int64
 1   age_first_milestone_year  923 non-null    int64
 2   age_last_milestone_year   923 non-null    int64
 3   relationships             923 non-null    int64
 4   funding_rounds            923 non-null    int64
 5   funding_total_usd         923 non-null    int64
 6   milestones                923 non-null    int64
 7   is_otherstate             923 non-null    int64
 8   has_roundA                923 non-null    int64
 9   has_roundB                923 non-null    int64
 10  has_roundC                923 non-null    int64
 11  has_roundD                923 non-null    int64
 12  avg_participants          923 non-null    int64
 13  is_top500                 923 non-null    int64
 14  status                    923 non-null    

In [12]:
# pip install sklearn_pandas

In [13]:
X = df2.drop(['status'],axis=1)
Y = df2['status']

In [16]:
Y.shape

(923,)

In [17]:
#covert numerical format
from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [24]:
df2.to_csv("new.csv")

In [25]:
df2

age_last_funding_year  age_first_milestone_year  age_last_milestone_year  \
0                        3                         4                        6   
1                        9                         7                        7   
2                        1                         1                        2   
3                        5                         6                        6   
4                        1                         0                        0   
..                     ...                       ...                      ...   
918                      0                         0                        4   
919                      9                         6                        6   
920                      8                         9                        9   
921                      2                         0                        3   
922                      3                         4                        4   

     relationships  funding_rounds  funding_total_usd  milestones  \
0                3               3             375000           3   
1                9               4           40100000           1   
2                5               1            2600000           2   
3                5               3           40000000           1   
4                2               2            1300000           1   
..             ...             ...                ...         ...   
918              9               1            1100000           2   
919              1               3           52000000           1   
920              5               1           44000000           1   
921             12               2           15500000           2   
922              4               1           20000000           1   

     is_otherstate  has_roundA  has_roundB  has_roundC  has_roundD  \
0                0           0           0           0           0   
1                0           0           1           1           1   
2                0           1           0           0           0   
3                0           0           1           1           1   
4                0           0           0           0           0   
..             ...         ...         ...         ...         ...   
918              0           1           0           0           0   
919              0           0           1           0           0   
920              0           0           0           0           1   
921              0           1           1           0           0   
922              0           0           1           0           0   

     avg_participants  is_top500  status  closed_at_year  closed_at_month  \
0                   1          0       1            2024               11   
1                   4          1       1            2024               11   
2                   4          1       1            2024               11   
3                   3          1       1            2024               11   
4                   1          1       0            2012                1   
..                ...        ...     ...             ...              ...   
918                 6          1       1            2024               11   
919                 2          1       0            2024               11   
920                 8          1       0            2024               11   
921                 1          1       1            2024               11   
922                 3          1       1            2024               11   

     first_funding_at_year  
0                     2009  
1                     2005  
2                     2010  
3                     2005  
4                     2010  
..                     ...  
918                   2009  
919                   2005  
920                   2007  
921                   2009  
922                   2006  

[923 rows x 18 columns]

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age_last_funding_year     923 non-null    int64
 1   age_first_milestone_year  923 non-null    int64
 2   age_last_milestone_year   923 non-null    int64
 3   relationships             923 non-null    int64
 4   funding_rounds            923 non-null    int64
 5   funding_total_usd         923 non-null    int64
 6   milestones                923 non-null    int64
 7   is_otherstate             923 non-null    int64
 8   has_roundA                923 non-null    int64
 9   has_roundB                923 non-null    int64
 10  has_roundC                923 non-null    int64
 11  has_roundD                923 non-null    int64
 12  avg_participants          923 non-null    int64
 13  is_top500                 923 non-null    int64
 14  status                    923 non-null    

In [27]:
df2['age_last_funding_year'].unique()

array([ 3,  9,  1,  5,  4,  6, 11,  2,  8,  7,  0, 10, 20, -1, 16, 12, 14,
       -9, 21, 13])

In [28]:
df2['age_first_milestone_year'].unique()

array([  4,   7,   1,   6,   0,   5,   3,   8,   2,  10,  -1,   9, -14,
        11,  -2,  12,  16,  -6,  -3,  13,  24,  15,  -7])

In [29]:
df2['age_last_milestone_year'].unique()

array([ 6,  7,  2,  0,  5,  9, 10,  4,  8, 12,  3,  1, -1, 11, 13, 14, 18,
       -3, 24, 15, -7])

In [30]:
df2['relationships'].unique()

array([ 3,  9,  5,  2,  6, 25, 13, 14, 22,  8,  0, 15, 12,  7, 10,  1,  4,
       37, 18, 26, 11, 17, 24, 16, 21, 27, 30, 33, 32, 23, 57, 20, 35, 19,
       45, 31, 29, 63, 42, 28, 38])

In [31]:
df2['funding_rounds'].unique()

array([ 3,  4,  1,  2,  5,  7,  6, 10,  8])

In [32]:
df2['funding_total_usd'].unique()

array([    375000,   40100000,    2600000,   40000000,    1300000,
          7500000,   26000000,   34100000,    9650000,    5750000,
         27500000,   10400000,     350000,    9950000,   10700000,
           200000,   49000000,   25000000,    4575000,   28000000,
          4355000,   15000000,    3170000,    2300000,     455000,
         13000000,    3800000,  299500000,    1000000,   10500000,
          8600000,    5000000,    2304999,      25000,    4000000,
         14600000,   44000000,    1822922,   29915001,   33000000,
           125000,   10000000,    6000000,    3750000,    3000000,
          1155000,   11500000,   29000000,   34700000,   12050000,
         12000000,    5500000,   24000000,   19009671,   18914576,
          2030882,   20500000,   13250000,   11489687,     355000,
           118000,   40400000,   19700000,   17800000,   57500000,
         17200000,     457282,   18500000,  510000000,   18250000,
         41500019,   42700000,   22300000,   15564591,     500

In [33]:
df2['funding_total_usd'].describe()

count    9.230000e+02
mean     2.541975e+07
std      1.896344e+08
min      1.100000e+04
25%      2.725000e+06
50%      1.000000e+07
75%      2.472500e+07
max      5.700000e+09
Name: funding_total_usd, dtype: float64

In [34]:
df2['milestones'].unique()

array([3, 1, 2, 4, 0, 5, 6, 8])

In [35]:
df2['is_otherstate'].unique()

array([0, 1])

In [36]:
df2['avg_participants'].unique()

array([ 1,  4,  3,  2,  5,  9,  6,  7, 10,  8, 12, 11, 16])

In [37]:
df2['closed_at_year'].unique()

array([2024, 2012, 2011, 2013, 2010, 2008, 2009, 2001, 2005, 2007])

In [38]:
df2['closed_at_month'].unique()

array([11,  1,  2, 10,  7,  4,  3,  8,  6,  9, 12,  5])

In [39]:
df2['first_funding_at_year'].unique()

array([2009, 2005, 2010, 2006, 2007, 2008, 2003, 2012, 2011, 2002, 2001,
       2004, 2013, 2000])

In [ ]:
# dm = DataFrameMapper([
#     (["closed_at",LabelEncoder()]),
#     (["first_funding_at",LabelEncoder()])
    
#                       ])

In [18]:
X = df2.drop(['status'],axis=1)
Y = df2['status']

In [19]:
X

age_last_funding_year  age_first_milestone_year  age_last_milestone_year  \
0                        3                         4                        6   
1                        9                         7                        7   
2                        1                         1                        2   
3                        5                         6                        6   
4                        1                         0                        0   
..                     ...                       ...                      ...   
918                      0                         0                        4   
919                      9                         6                        6   
920                      8                         9                        9   
921                      2                         0                        3   
922                      3                         4                        4   

     relationships  funding_rounds  funding_total_usd  milestones  \
0                3               3             375000           3   
1                9               4           40100000           1   
2                5               1            2600000           2   
3                5               3           40000000           1   
4                2               2            1300000           1   
..             ...             ...                ...         ...   
918              9               1            1100000           2   
919              1               3           52000000           1   
920              5               1           44000000           1   
921             12               2           15500000           2   
922              4               1           20000000           1   

     is_otherstate  has_roundA  has_roundB  has_roundC  has_roundD  \
0                0           0           0           0           0   
1                0           0           1           1           1   
2                0           1           0           0           0   
3                0           0           1           1           1   
4                0           0           0           0           0   
..             ...         ...         ...         ...         ...   
918              0           1           0           0           0   
919              0           0           1           0           0   
920              0           0           0           0           1   
921              0           1           1           0           0   
922              0           0           1           0           0   

     avg_participants  is_top500  closed_at_year  closed_at_month  \
0                   1          0            2024               11   
1                   4          1            2024               11   
2                   4          1            2024               11   
3                   3          1            2024               11   
4                   1          1            2012                1   
..                ...        ...             ...              ...   
918                 6          1            2024               11   
919                 2          1            2024               11   
920                 8          1            2024               11   
921                 1          1            2024               11   
922                 3          1            2024               11   

     first_funding_at_year  
0                     2009  
1                     2005  
2                     2010  
3                     2005  
4                     2010  
..                     ...  
918                   2009  
919                   2005  
920                   2007  
921                   2009  
922                   2006  

[923 rows x 17 columns]

In [20]:
Y

0      1
1      1
2      1
3      1
4      0
      ..
918    1
919    0
920    0
921    1
922    1
Name: status, Length: 923, dtype: int64

In [21]:
ml =[]
# ml.append(['mapper',dm])
ml.append(['sc',StandardScaler()])
ml.append(['RF',RandomForestClassifier()])
ml

[['sc', StandardScaler()], ['RF', RandomForestClassifier()]]

In [22]:
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')

In [23]:
model = Pipeline(ml)
model.fit(X,Y)

Pipeline(steps=[('sc', StandardScaler()), ['RF', RandomForestClassifier()]])

In [40]:
dict(df2.iloc[5,:])

{'age_last_funding_year': np.int64(4),
 'age_first_milestone_year': np.int64(5),
 'age_last_milestone_year': np.int64(5),
 'relationships': np.int64(3),
 'funding_rounds': np.int64(1),
 'funding_total_usd': np.int64(7500000),
 'milestones': np.int64(1),
 'is_otherstate': np.int64(0),
 'has_roundA': np.int64(0),
 'has_roundB': np.int64(1),
 'has_roundC': np.int64(0),
 'has_roundD': np.int64(0),
 'avg_participants': np.int64(3),
 'is_top500': np.int64(1),
 'status': np.int64(0),
 'closed_at_year': np.int64(2024),
 'closed_at_month': np.int64(11),
 'first_funding_at_year': np.int64(2006)}

In [41]:
import numpy as np
data ={'age_last_funding_year': np.int64(4),
 'age_first_milestone_year': np.int64(5),
 'age_last_milestone_year': np.int64(5),
 'relationships': np.int64(3),
 'funding_rounds': np.int64(1),
 'funding_total_usd': np.int64(7500000),
 'milestones': np.int64(1),
 'is_otherstate': np.int64(0),
 'has_roundA': np.int64(0),
 'has_roundB': np.int64(1),
 'has_roundC': np.int64(0),
 'has_roundD': np.int64(0),
 'avg_participants': np.int64(3),
 'is_top500': np.int64(1),

 'closed_at_year': np.int64(2024),
 'closed_at_month': np.int64(11),
 'first_funding_at_year': np.int64(2006)}

new_data = pd.DataFrame(data,index=[0])
new_data

age_last_funding_year  age_first_milestone_year  age_last_milestone_year  \
0                      4                         5                        5   

   relationships  funding_rounds  funding_total_usd  milestones  \
0              3               1            7500000           1   

   is_otherstate  has_roundA  has_roundB  has_roundC  has_roundD  \
0              0           0           1           0           0   

   avg_participants  is_top500  closed_at_year  closed_at_month  \
0                 3          1            2024               11   

   first_funding_at_year  
0                   2006

In [42]:
model.predict(new_data)

array([0])

In [43]:
import pickle
with open('final_model.sav',mode='wb')as f:
    pickle.dump(model,f)

In [44]:
df2.describe()

age_last_funding_year  age_first_milestone_year  \
count             923.000000                923.000000   
mean                3.477790                  2.293608   
std                 2.938689                  2.840945   
min                -9.000000                -14.000000   
25%                 1.000000                  0.000000   
50%                 3.000000                  2.000000   
75%                 5.000000                  4.000000   
max                21.000000                 24.000000   

       age_last_milestone_year  relationships  funding_rounds  \
count               923.000000     923.000000      923.000000   
mean                  3.640303       7.710726        2.310943   
std                   3.305911       7.265776        1.390922   
min                  -7.000000       0.000000        1.000000   
25%                   1.000000       3.000000        1.000000   
50%                   3.000000       5.000000        2.000000   
75%                   6.000000      10.000000        3.000000   
max                  24.000000      63.000000       10.000000   

       funding_total_usd  milestones  is_otherstate  has_roundA  has_roundB  \
count       9.230000e+02  923.000000     923.000000  923.000000  923.000000   
mean        2.541975e+07    1.841820       0.221018    0.508126    0.392199   
std         1.896344e+08    1.322632       0.415158    0.500205    0.488505   
min         1.100000e+04    0.000000       0.000000    0.000000    0.000000   
25%         2.725000e+06    1.000000       0.000000    0.000000    0.000000   
50%         1.000000e+07    2.000000       0.000000    1.000000    0.000000   
75%         2.472500e+07    3.000000       0.000000    1.000000    1.000000   
max         5.700000e+09    8.000000       1.000000    1.000000    1.000000   

       has_roundC  has_roundD  avg_participants   is_top500      status  \
count  923.000000  923.000000        923.000000  923.000000  923.000000   
mean     0.232936    0.099675          2.679307    0.809317    0.646804   
std      0.422931    0.299729          1.859219    0.393052    0.478222   
min      0.000000    0.000000          1.000000    0.000000    0.000000   
25%      0.000000    0.000000          1.000000    1.000000    0.000000   
50%      0.000000    0.000000          2.000000    1.000000    1.000000   
75%      0.000000    0.000000          3.000000    1.000000    1.000000   
max      1.000000    1.000000         16.000000    1.000000    1.000000   

       closed_at_year  closed_at_month  first_funding_at_year  
count      923.000000       923.000000             923.000000  
mean      2020.833153         8.839653            2007.475623  
std          5.493864         3.988904               2.293583  
min       2001.000000         1.000000            2000.000000  
25%       2013.000000        11.000000            2006.000000  
50%       2024.000000        11.000000            2007.000000  
75%       2024.000000        11.000000            2009.000000  
max       2024.000000        12.000000            2013.000000

In [45]:
df2

age_last_funding_year  age_first_milestone_year  age_last_milestone_year  \
0                        3                         4                        6   
1                        9                         7                        7   
2                        1                         1                        2   
3                        5                         6                        6   
4                        1                         0                        0   
..                     ...                       ...                      ...   
918                      0                         0                        4   
919                      9                         6                        6   
920                      8                         9                        9   
921                      2                         0                        3   
922                      3                         4                        4   

     relationships  funding_rounds  funding_total_usd  milestones  \
0                3               3             375000           3   
1                9               4           40100000           1   
2                5               1            2600000           2   
3                5               3           40000000           1   
4                2               2            1300000           1   
..             ...             ...                ...         ...   
918              9               1            1100000           2   
919              1               3           52000000           1   
920              5               1           44000000           1   
921             12               2           15500000           2   
922              4               1           20000000           1   

     is_otherstate  has_roundA  has_roundB  has_roundC  has_roundD  \
0                0           0           0           0           0   
1                0           0           1           1           1   
2                0           1           0           0           0   
3                0           0           1           1           1   
4                0           0           0           0           0   
..             ...         ...         ...         ...         ...   
918              0           1           0           0           0   
919              0           0           1           0           0   
920              0           0           0           0           1   
921              0           1           1           0           0   
922              0           0           1           0           0   

     avg_participants  is_top500  status  closed_at_year  closed_at_month  \
0                   1          0       1            2024               11   
1                   4          1       1            2024               11   
2                   4          1       1            2024               11   
3                   3          1       1            2024               11   
4                   1          1       0            2012                1   
..                ...        ...     ...             ...              ...   
918                 6          1       1            2024               11   
919                 2          1       0            2024               11   
920                 8          1       0            2024               11   
921                 1          1       1            2024               11   
922                 3          1       1            2024               11   

     first_funding_at_year  
0                     2009  
1                     2005  
2                     2010  
3                     2005  
4                     2010  
..                     ...  
918                   2009  
919                   2005  
920                   2007  
921                   2009  
922                   2006  

[923 rows x 18 columns]

In [46]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age_last_funding_year     923 non-null    int64
 1   age_first_milestone_year  923 non-null    int64
 2   age_last_milestone_year   923 non-null    int64
 3   relationships             923 non-null    int64
 4   funding_rounds            923 non-null    int64
 5   funding_total_usd         923 non-null    int64
 6   milestones                923 non-null    int64
 7   is_otherstate             923 non-null    int64
 8   has_roundA                923 non-null    int64
 9   has_roundB                923 non-null    int64
 10  has_roundC                923 non-null    int64
 11  has_roundD                923 non-null    int64
 12  avg_participants          923 non-null    int64
 13  is_top500                 923 non-null    int64
 14  status                    923 non-null    